#!/usr/bin/env python3
import json
import sys

"""
Usage: extract-config PATH_TO_CONFIG
"""


def run(config_path):
    with open(config_path) as json_data:
        d = json.load(json_data)
        port = d["port"]
        name = d["name"]
        cache_volume = d["cache_volume"]
        with open("config.sh", "w+") as f:
            f.write("port={}\n".format(port))
            f.write("name={}\n".format(name))
            f.write("cache_volume={}".format(cache_volume))


if __name__ == "__main__":
    run(sys.argv[1])
