#!/usr/bin/env python3
import json

config_path = "config.json"


def run():
    with open(config_path) as json_data:
        d = json.load(json_data)
        port = d["port"]
        tag = d["tag"]
        cache_volume = d["cache_volume"]
        with open("config.sh", "w+") as f:
            f.write("port={}\n".format(port))
            f.write("tag={}\n".format(tag))
            f.write("name={}_1\n".format(tag))
            f.write("cache_volume={}".format(cache_volume))


if __name__ == "__main__":
    run()
